"""
╔══════════════════════════════════════════════════════════════════════════════╗
║   figure4_bar.py  —  Delphi Platform  ·  double-column Figure 4          ║
╚══════════════════════════════════════════════════════════════════════════════╝

QUICK START
───────────
  python utils/Figure4.py \
      --excel  /path/to/delphi/data/Figure4_data.xlsx \
      --jain   /path/to/delphi/data/Jain2017_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \
      --gdpa1  /path/to/delphi/data/GDPa1_v1.3_20251027_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \
      --gdpa3  /path/to/delphi/data/GDPa3_20260106_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \
      --out    Figure4 \
      --dpi    300

  # Separate panels only
  python utils/Figure4.py \\
      --excel  ... --jain ... --gdpa1 ... --gdpa3 ...
      --out Figure4 --dpi 300 --panels-only

DESCRIPTION
───────────
Generates a 4-panel double-column figure (183 x 216 mm, 300 DPI) showing:

  a  IPI PSR Dataset · 10-Fold HCDR3-Stratified CV
     Grouped bar chart — AUC-ROC + Accuracy per Language Model,
     grouped by ML Architecture (CNN / Transformer / RF / XGBoost)

  b  Cross-Dataset Generalization · Transformer Architecture
     Grouped bar chart — AUC-ROC + Accuracy per Language Model,
     grouped by transfer condition (DS1 10-fold CV / DS1→IPI / IPI→DS1)

  c  External Clinical Antibody Validation — AUC-ROC Heatmap
     IPI PSR transformer model predictions vs 3 external datasets:
       • Jain 2017    (n=137, PSR SMP + ELISA)
       • GDPa1        (n=197, PR Ova + PR CHO)
       • GDPa3 / Ginkgo (n=80, PR Ova + PR CHO)
     PASS thresholds: PSR/PR < 0.27 (Jain 2017 90th-pct);  ELISA < 1.9

  d  External Clinical Antibody Validation — Spearman ρ Heatmap
     Spearman correlation between IPI model P(PASS) scores and raw assay
     values. Significance stars: *** p<0.001  ** p<0.01  * p<0.05  ns

REQUIRED INPUT FILES
────────────────────
  --excel    Figure4_data.xlsx
               Two sheets (auto-read):
                 • Fig5A_IPI_10fold_CV   → panels a, b (bar charts)
                 • Fig5B_Cross_Dataset   → panels a, b (bar charts)
               Expected columns: Architecture, Language Model, AUC, Accuracy,
                                  Precision, Recall, F1-Score, Condition

  --jain     Jain2017_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx
               IPI model predictions on Jain 2017 (n=137) clinical antibodies.
               Required columns: BARCODE, PSR_SMP_Score, ELISA,
                                  transformer_lm_{lm}_ipi_psr_trainset_score
               (generated by: python predict_developability.py --predict Jain2017.xlsx ...)

  --gdpa1    GDPa1_v1_3_20251027_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx
               IPI model predictions on GDPa1 (n=197, Ginkgo Datapoints).
               Required columns: BARCODE, polyreactivity_prscore_ova_avg,
                                  polyreactivity_prscore_cho_avg,
                                  transformer_lm_{lm}_ipi_psr_trainset_score

  --gdpa3    GDPa3_20260106_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx
               IPI model predictions on GDPa3 (n=80, Ginkgo competition test set).
               Required columns: BARCODE, polyreactivity_prscore_ova_avg,
                                  polyreactivity_prscore_cho_avg, psr_filter_ova,
                                  psr_filter_cho,
                                  transformer_lm_{lm}_ipi_psr_trainset_score

HOW TO GENERATE PREDICTION FILES
──────────────────────────────────
  # Predict on Jain 2017 (all LMs at once)
  python predict_developability.py \\
      --target psr_filter \\
      --lm ablang,antiberty,antiberta2,antiberta2-cssp,igbert \\
      --model transformer_lm \\
      --db data/ipi_psr_trainset.xlsx \\
      --predict external/Jain2017.xlsx

  # Predict on GDPa1
  python predict_developability.py \\
      --target psr_filter \\
      --lm ablang,antiberty,antiberta2,antiberta2-cssp,igbert \\
      --model transformer_lm \\
      --db data/ipi_psr_trainset.xlsx \\
      --predict external/GDPa1_v1_3_20251027.xlsx

  # Predict on GDPa3
  python predict_developability.py \\
      --target psr_filter \\
      --lm ablang,antiberty,antiberta2,antiberta2-cssp,igbert \\
      --model transformer_lm \\
      --db data/ipi_psr_trainset.xlsx \\
      --predict external/GDPa3_20260106.xlsx

USAGE
─────
  # Minimal (uses default filenames in current directory)
  python figure4_bar.py

  # Full explicit paths
  python utils/Figure4.py \\
      --excel  /path/to/delphi/manuscripts/figures_tables/Figure4_data.xlsx \\
      --jain   /path/to/delphi/manuscripts/data/public_clinical/Jain2017_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \\
      --gdpa1  /path/to/delphi/manuscripts/data/public_clinical/GDPa1_v1.3_20251027_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \\
      --gdpa3  /path/to/delphi/manuscripts/data/public_clinical/GDPa3_20260106_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \\
      --out    Figure4 \\
      --dpi    300

OUTPUTS
───────
  {out}.tiff          High-resolution TIFF (300 DPI) — for journal submission
  {out}_preview.png   Low-resolution PNG  (150 DPI) — for quick preview

CUSTOMISATION (edit Section 0 constants at top of script)
──────────────────────────────────────────────────────────
  FW, FH              Figure width / height in mm  (default: 183 × 216 mm)
  AUC_COL, ACC_COL    Bar colours for AUC and Accuracy
  THRESH              Polyreactivity PASS threshold for AUC panels (default 0.27)
  THRESH_ELISA        ELISA PASS threshold (default 1.9 — Jain 2017 paper value)
  ARCH_LMS            LMs shown per architecture block in panel a
  ARCH_ORDER          Order of architecture blocks in panel a

DEPENDENCIES
────────────
  pip install pandas openpyxl scipy scikit-learn matplotlib mpl-toolkits

REFERENCE THRESHOLDS (Jain 2017, PNAS 114:944-949)
────────────────────────────────────────────────────
  PSR SMP   < 0.27   90th percentile of 48 FDA-approved antibodies (actual: 0.263)
  ELISA     < 1.9    90th percentile of 48 FDA-approved antibodies (OD ratio scale)
  PR Ova    < 0.27   Unified with Ginkgo PROPHET-Ab 2025 platform threshold
  PR CHO    < 0.27   Unified with Ginkgo PROPHET-Ab 2025 platform threshold
"""
# ── ALL ORIGINAL IMPORTS & CONSTANTS ─────────────────────────────────────────
# (copied verbatim from figure4_bar.py — not changed)

"""
figure4_panels_separate.py
──────────────────────────
Generates panels a, b, c from figure4_bar.py as SEPARATE high-resolution files.

NOTHING changed from figure4_bar.py except:
  • main() now saves each panel as its own figure
  • --dpi flag controls output resolution (default 300; use 600 for print)

USAGE
─────
  python figure4_panels_separate.py \\
      --excel  Figure4_data.xlsx \\
      --jain   Jain2017_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \\
      --gdpa1  GDPa1_v1_3_20251027_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \\
      --gdpa3  GDPa3_20260106_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx \\
      --out    Figure4 \\
      --dpi    300

OUTPUTS
───────
  Figure4_panel_a.tiff   Panel a — IPI PSR 10-Fold CV bar chart
  Figure4_panel_b.tiff   Panel b — Cross-Dataset Generalization bar chart
  Figure4_panel_c.tiff   Panel c — Clinical AUC-ROC heatmap
  Figure4_panel_a.png    Preview PNG (150 DPI)
  Figure4_panel_b.png    Preview PNG
  Figure4_panel_c.png    Preview PNG
"""

# ── ALL ORIGINAL IMPORTS & CONSTANTS ─────────────────────────────────────────

import argparse
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.colors as mcolors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from scipy.stats import spearmanr
from sklearn.metrics import roc_auc_score
import matplotlib.ticker as ticker
from matplotlib.gridspec import GridSpec
from pathlib import Path
import os

MM   = 1 / 25.4
FW   = 183 * MM
FH   = 120 * MM
DPI  = 300
FONT = "Arial"

AUC_COL = "#2166AC"
ACC_COL = "#92C5DE"

ARCH_COL = {
    "CNN"        : "#0072B2",
    "Transformer": "#E69F00",
    "RF"         : "#009E73",
    "XGBoost"    : "#CC79A7",
}

COND_COL = {
    "DS1 10-fold CV": "#0072B2",
    "DS1 → IPI"     : "#D55E00",
    "IPI → DS1"     : "#009E73",
}
COND_MAP = {
    "DS1 · 10-Fold CV"  : "DS1 10-fold CV",
    "DS1 → IPI Transfer": "DS1 → IPI",
    "IPI → DS1 Transfer": "IPI → DS1",
}

LM_SHORT = {
    "AbLang2"        : "AbLang2",
    "AntiBERTy"      : "AntiBERTy",
    "AntiBERTa2"     : "AntiBERTa2",
    "AntiBERTa2-CSSP": "AntiBERTa2-CSSP",
    "IgBert"         : "IgBert",
    "One-hot"        : "One-hot",
    "Biophysical"    : "Biophysical",
    "k-mer"          : "k-mer",
}

THRESH         = 0.27
THRESH_ELISA   = 1.9
HM_LM_ORDER   = ['ablang','antiberty','antiberta2','antiberta2-cssp','igbert','onehot']
HM_LM_DISPLAY = ['AbLang2','AntiBERTy','AntiBERTa2','AntiBERTa2-CSSP','IgBert','One-hot']
DATASETS_AUC  = ['Jain 2017\nPSR SMP','Jain 2017\nELISA','GDPa1\nPR Ova','GDPa1\nPR CHO','GDPa3\nPR Ova','GDPa3\nPR CHO']
DATASETS_RHO  = ['Jain 2017\nPSR SMP','Jain 2017\nELISA','GDPa1\nPR Ova','GDPa1\nPR CHO','GDPa3\nPR Ova','GDPa3\nPR CHO']

BAR_W     = 0.35
BAR_GAP   = 0.02
GROUP_GAP = 0.9

matplotlib.rcParams.update({
    "font.family"       : "sans-serif",
    "font.sans-serif"   : [FONT, "Helvetica", "DejaVu Sans"],
    "font.size"         : 6,
    "axes.labelsize"    : 6.5,
    "axes.titlesize"    : 7,
    "axes.linewidth"    : 0.5,
    "axes.spines.top"   : False,
    "axes.spines.right" : False,
    "xtick.labelsize"   : 5.5,
    "ytick.labelsize"   : 5.5,
    "xtick.major.width" : 0.5,
    "ytick.major.width" : 0.5,
    "xtick.major.size"  : 0,
    "ytick.major.size"  : 2,
    "xtick.direction"   : "out",
    "ytick.direction"   : "out",
    "legend.fontsize"   : 6,
    "legend.frameon"    : False,
    "pdf.fonttype"      : 42,
    "ps.fonttype"       : 42,
})

ARCH_ORDER = ["CNN", "Transformer", "RF", "XGBoost"]
ARCH_LMS   = {
    "CNN"        : ["AbLang2","AntiBERTy","AntiBERTa2","AntiBERTa2-CSSP","IgBert"],
    "Transformer": ["AbLang2","AntiBERTy","AntiBERTa2","AntiBERTa2-CSSP","IgBert","One-hot"],
    "RF"         : ["AbLang2","AntiBERTy","AntiBERTa2","AntiBERTa2-CSSP","IgBert","Biophysical","k-mer"],
    "XGBoost"    : ["AbLang2","AntiBERTy","AntiBERTa2","AntiBERTa2-CSSP","IgBert","Biophysical","k-mer"],
}
COND_ORDER = ["DS1 10-fold CV", "DS1 → IPI", "IPI → DS1"]


# ── ALL ORIGINAL FUNCTIONS ────────────────────────────────────────────────────


def load_data(excel_path):
    df_cv = pd.read_excel(excel_path, sheet_name='Fig4A_IPI_10fold_CV', skiprows=1)
    df_cv.columns = df_cv.columns.str.strip()
    df_cv['Architecture'] = df_cv['Architecture'].ffill()
    df_cv = df_cv.dropna(subset=['Language Model'])
    df_cv = df_cv.rename(columns={'Language Model': 'LM', 'F1-Score': 'F1'})

    df_xfer = pd.read_excel(excel_path, sheet_name='Fig4B_Cross_Dataset', skiprows=1)
    df_xfer.columns = df_xfer.columns.str.strip()
    df_xfer['Condition'] = df_xfer['Condition'].ffill()
    df_xfer = df_xfer.dropna(subset=['Language Model'])
    df_xfer = df_xfer.rename(columns={'Language Model': 'LM', 'F1-Score': 'F1'})
    df_xfer['cond'] = df_xfer['Condition'].map(COND_MAP)
    return df_cv, df_xfer


def draw_bar_panel(ax, groups, title, panel_letter, ylim=(0.84, 1.00),
                   ref_auc=None, ref_acc=None, group_col=None):
    x_ticks, x_tick_labels, group_centres = [], [], {}
    cursor = 0.0
    for g_idx, (g_label, lm_rows) in enumerate(groups):
        g_start = cursor
        for lm_label, auc_val, acc_val in lm_rows:
            x_auc = cursor
            x_acc = cursor + BAR_W + BAR_GAP
            ax.bar(x_auc, auc_val - ylim[0], BAR_W,
                   bottom=ylim[0], color=AUC_COL, zorder=3, linewidth=0, clip_on=False)
            ax.bar(x_acc, acc_val - ylim[0], BAR_W,
                   bottom=ylim[0], color=ACC_COL, zorder=3, linewidth=0, clip_on=False)
            tick_x = cursor + (BAR_W * 2 + BAR_GAP) / 2
            x_ticks.append(tick_x)
            x_tick_labels.append(lm_label)
            cursor += BAR_W * 2 + BAR_GAP + 0.12
        g_end = cursor - 0.12
        group_centres[g_label] = (g_start, g_end)
        cursor += GROUP_GAP

    total_width = cursor - GROUP_GAP + 0.2
    ax.set_xlim(-0.4, total_width)
    ax.set_ylim(ylim)
    ax.yaxis.set_major_locator(ticker.MultipleLocator(0.1))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(0.05))
    ax.tick_params(axis='y', which='minor', length=1.2, width=0.4)
    ax.set_ylabel('Score', fontsize=6.5, labelpad=3)
    ax.grid(axis='y', lw=0.25, alpha=0.4, zorder=0)
    ax.set_xticks(x_ticks)
    ax.set_xticklabels(x_tick_labels, rotation=40, ha='right',
                       rotation_mode='anchor', fontsize=5.5)

    if ref_auc:
        ax.axhline(ref_auc, color=AUC_COL, lw=0.7, ls='--', alpha=0.6, zorder=2)
        ax.text(total_width, ref_auc, f' ≥{ref_auc}',
                color=AUC_COL, fontsize=5, va='center')
    if ref_acc:
        ax.axhline(ref_acc, color=ACC_COL, lw=0.7, ls='--', alpha=0.6, zorder=2)
        ax.text(total_width, ref_acc, f' ≥{ref_acc}',
                color=ACC_COL, fontsize=5, va='center')

    for g_label, (g_s, g_e) in group_centres.items():
        xm  = (g_s + g_e) / 2
        col = (group_col or {}).get(g_label, '#333333')
        ax.annotate('', xy=(g_s - 0.05, -0.18), xycoords=('data', 'axes fraction'),
                    xytext=(g_e + 0.05, -0.18), textcoords=('data', 'axes fraction'),
                    arrowprops=dict(arrowstyle='-', color=col, lw=1.0))
        ax.text(xm, -0.20, g_label, transform=ax.get_xaxis_transform(),
                ha='center', va='top', fontsize=6.5,
                fontweight='bold', color=col)

    ax.set_title(title, fontsize=6.5, pad=6, fontweight='bold', loc='left')
    ax.text(-0.07, 1.08, panel_letter,
            transform=ax.transAxes, fontsize=9, fontweight='bold',
            va='top', ha='left')

    patch_auc = mpatches.Patch(color=AUC_COL, label='AUC-ROC')
    patch_acc = mpatches.Patch(color=ACC_COL, label='Accuracy')
    leg = ax.legend(handles=[patch_auc, patch_acc],
                    loc='lower right', bbox_to_anchor=(0.99, 0.01),
                    fontsize=6, handlelength=1.0, handletextpad=0.4,
                    labelspacing=0.25, borderpad=0.4,
                    frameon=True, framealpha=0.92,
                    edgecolor='#CCCCCC', fancybox=False)
    leg.get_frame().set_linewidth(0.4)


def score_col(lm):
    if lm == 'onehot': return 'transformer_onehot_onehot_ipi_psr_trainset_score'
    return f'transformer_lm_{lm}_ipi_psr_trainset_score'

def safe_auc(df, sc, assay_col, min_fail=5, thresh=None):
    sub = df[[sc, assay_col]].dropna()
    t   = thresh if thresh is not None else THRESH
    y   = (sub[assay_col] < t).astype(int)
    if (y==0).sum() < min_fail or (y==1).sum() < min_fail: return np.nan
    return roc_auc_score(y, sub[sc])

def safe_rho_p(df, sc, assay_col):
    sub = df[[sc, assay_col]].dropna()
    if len(sub) < 5: return np.nan, np.nan
    r, p = spearmanr(sub[sc], sub[assay_col])
    return r, p

def compute_heatmap_matrices(jain, gdpa1, gdpa3):
    n   = len(HM_LM_ORDER)
    auc = np.full((n, len(DATASETS_AUC)), np.nan)
    rho = np.full((n, len(DATASETS_RHO)), np.nan)
    pv  = np.full((n, len(DATASETS_RHO)), np.nan)
    for i, lm in enumerate(HM_LM_ORDER):
        c = score_col(lm)
        if c in jain.columns:
            auc[i,0] = safe_auc(jain, c, 'PSR_SMP_Score')
            auc[i,1] = safe_auc(jain, c, 'ELISA', thresh=THRESH_ELISA)
            rho[i,0], pv[i,0] = safe_rho_p(jain, c, 'PSR_SMP_Score')
            rho[i,1], pv[i,1] = safe_rho_p(jain, c, 'ELISA')
        if c in gdpa1.columns:
            auc[i,2] = safe_auc(gdpa1, c, 'polyreactivity_prscore_ova_avg')
            auc[i,3] = safe_auc(gdpa1, c, 'polyreactivity_prscore_cho_avg')
            rho[i,2], pv[i,2] = safe_rho_p(gdpa1, c, 'polyreactivity_prscore_ova_avg')
            rho[i,3], pv[i,3] = safe_rho_p(gdpa1, c, 'polyreactivity_prscore_cho_avg')
        if c in gdpa3.columns:
            auc[i,4] = safe_auc(gdpa3, c, 'polyreactivity_prscore_ova_avg', min_fail=3)
            auc[i,5] = safe_auc(gdpa3, c, 'polyreactivity_prscore_cho_avg')
            rho[i,4], pv[i,4] = safe_rho_p(gdpa3, c, 'polyreactivity_prscore_ova_avg')
            rho[i,5], pv[i,5] = safe_rho_p(gdpa3, c, 'polyreactivity_prscore_cho_avg')
    return auc, rho, pv

def _sig_stars(p):
    if np.isnan(p): return ''
    if p < 0.001:   return '***'
    if p < 0.01:    return '**'
    if p < 0.05:    return '*'
    return 'ns'

def draw_heatmap(ax, mat, row_labels, col_labels,
                 title, panel_letter,
                 vmin, vmax, vcenter,
                 cmap='RdBu_r', fmt='.2f', cbar_label='',
                 col_sep=None, grp_labels=None, cbar_ticks=None,
                 pval_mat=None):
    n_r, n_c = mat.shape
    norm = mcolors.TwoSlopeNorm(vmin=vmin, vcenter=vcenter, vmax=vmax)
    im   = ax.imshow(mat, aspect='auto', cmap=cmap, norm=norm,
                     interpolation='nearest', extent=[-0.5, n_c-0.5, n_r-0.5, -0.5])
    cmap_obj = plt.get_cmap(cmap)
    for i in range(n_r):
        for j in range(n_c):
            v = mat[i,j]
            if np.isnan(v):
                ax.text(j,i,'N/A',ha='center',va='center',fontsize=5,color='#888'); continue
            rgba = cmap_obj(norm(v))
            lum  = 0.299*rgba[0]+0.587*rgba[1]+0.114*rgba[2]
            tc   = 'white' if lum<0.45 else '#333333'
            fw   = 'bold' if abs(v-vcenter)>0.12 else 'normal'
            _star    = _sig_stars(pval_mat[i,j]) if pval_mat is not None else ''
            _val_str = format(v, fmt)
            if _star and _star != 'ns':
                _val_str = f"{_val_str}\n{_star}"
            elif _star == 'ns':
                _val_str = f"{_val_str}\nns"
            ax.text(j, i, _val_str, ha='center', va='center',
                    fontsize=5.5 if _star else 6.5,
                    color=tc, fontweight=fw, linespacing=1.2)

    ax.set_ylim(n_r - 0.5, -1.2)
    ax.set_xticks(range(n_c))
    ax.set_xticklabels(col_labels, fontsize=6, rotation=38,
                       ha='right', rotation_mode='anchor')
    ax.set_yticks(range(n_r))
    ax.set_yticklabels(row_labels, fontsize=6.5)
    ax.tick_params(length=0, pad=3)
    for sp in ax.spines.values(): sp.set_visible(False)
    ax.tick_params(top=False, bottom=False, left=False, right=False)

    if col_sep:
        for sep in col_sep:
            ax.axvline(sep+0.5, color='#555555', lw=1.2, ls='--', zorder=5)

    ax.set_title(title, fontsize=6.5, pad=8, fontweight='bold', loc='left')
    ax.text(-0.065, 1.18, panel_letter,
            transform=ax.transAxes, fontsize=9, fontweight='bold',
            va='top', ha='left')

    div = make_axes_locatable(ax)
    cax = div.append_axes('right', size='2%', pad=0.07)
    cb  = plt.colorbar(im, cax=cax)
    cb.set_label(cbar_label, fontsize=6, labelpad=3)
    if cbar_ticks is not None:
        cb.set_ticks(cbar_ticks)
        cb.ax.set_yticklabels([str(t) for t in cbar_ticks])
    cb.ax.tick_params(labelsize=5.5, length=2)
    for sp in ax.spines.values(): sp.set_visible(False)


def build_groups_a(df_cv):
    groups = []
    for arch in ARCH_ORDER:
        rows = []
        for lm in ARCH_LMS[arch]:
            sub = df_cv[(df_cv['Architecture']==arch) & (df_cv['LM']==lm)]
            if len(sub) == 0: continue
            rows.append((LM_SHORT.get(lm, lm),
                         float(sub['AUC'].iloc[0]),
                         float(sub['Accuracy'].iloc[0])))
        if rows:
            groups.append((arch, rows))
    return groups


def build_groups_b(df_xfer):
    groups = []
    for cond in COND_ORDER:
        sub = df_xfer[df_xfer['cond'] == cond]
        if sub.empty: continue
        rows = [(LM_SHORT.get(row['LM'], row['LM']),
                 float(row['AUC']), float(row['Accuracy']))
                for _, row in sub.iterrows()]
        if rows:
            groups.append((cond, rows))
    return groups


# ── NEW: save_panel helper ────────────────────────────────────────────────────

def save_panel(fig, stem, dpi):
    """Save one figure as TIFF + preview PNG."""
    tiff = f"{stem}.tiff"
    png  = f"{stem}_preview.png"
    fig.savefig(tiff, dpi=dpi, format='tiff',
                bbox_inches='tight', pad_inches=0.05, facecolor='white')
    fig.savefig(png,  dpi=150,
                bbox_inches='tight', pad_inches=0.05, facecolor='white')
    w, h = fig.get_size_inches()
    px_w = int(w * dpi)
    px_h = int(h * dpi)
    print(f"  → {tiff}  ({px_w}×{px_h} px, {dpi} DPI, {os.path.getsize(tiff)//1024} KB)")
    print(f"  → {png}  (preview)")
    plt.close(fig)


# ── ONLY CHANGE IS HERE: main() saves each panel separately ──────────────────


def save_combined(fig, stem, dpi):
    """Save combined figure as TIFF + preview PNG."""
    tiff = f"{stem}.tiff"
    png  = f"{stem}_preview.png"
    fig.savefig(tiff, dpi=dpi, format='tiff',
                bbox_inches='tight', pad_inches=0.05, facecolor='white')
    fig.savefig(png, dpi=150,
                bbox_inches='tight', pad_inches=0.05, facecolor='white')
    w, h = fig.get_size_inches()
    print(f"  → {tiff}  ({int(w*dpi)}×{int(h*dpi)} px, {dpi} DPI, {os.path.getsize(tiff)//1024} KB)")
    print(f"  → {png}  (preview)")
    plt.close(fig)


def make_combined_figure(groups_a, groups_b, auc_mat, rho_mat, pval_mat, out, dpi):
    """
    Generate combined 4-panel double-column Figure 4.
    Layout:
      Row 1: [panel a (wide) | panel b (narrow)]
      Row 2: [panel c (full width)             ]
      Row 3: [panel d (full width)             ]
    """
    FW_C = 183 * MM          # full NB text width
    FH_C = 230 * MM          # full page height

    fig = plt.figure(figsize=(FW_C, FH_C))
    gs  = GridSpec(
        3, 2,
        figure    = fig,
        height_ratios = [1.2, 0.9, 0.9],
        width_ratios  = [1.55, 1.0],
        hspace    = 0.55,
        wspace    = 0.12,
        left      = 0.09,
        right     = 0.97,
        top       = 0.97,
        bottom    = 0.07,
    )

    # Panel a — IPI PSR 10-fold CV (spans col 0, row 0)
    ax_a = fig.add_subplot(gs[0, 0])
    draw_bar_panel(
        ax_a, groups_a,
        title        = "IPI PSR Dataset · 10-Fold HCDR3-Stratified CV",
        panel_letter = "a",
        ylim         = (0.0, 1.02),
        ref_auc      = 0.960,
        ref_acc      = 0.900,
        group_col    = ARCH_COL,
    )

    # Panel b — Cross-dataset (spans col 1, row 0)
    ax_b = fig.add_subplot(gs[0, 1])
    draw_bar_panel(
        ax_b, groups_b,
        title        = "Cross-Dataset Generalization · Transformer",
        panel_letter = "b",
        ylim         = (0.0, 1.02),
        ref_auc      = 0.90,
        ref_acc      = None,
        group_col    = COND_COL,
    )

    # Panel c — AUC-ROC heatmap (spans both cols, row 1)
    ax_c = fig.add_subplot(gs[1, :])
    draw_heatmap(
        ax_c, auc_mat, HM_LM_DISPLAY, DATASETS_AUC,
        title        = (f"IPI PSR Transformer Model Validation on External Clinical Antibodies  —  "
                        f"AUC-ROC  (PASS: PSR/PR score <{THRESH}; ELISA <{THRESH_ELISA})"),
        panel_letter = "c",
        vmin=0.20, vmax=0.90, vcenter=0.55,
        cmap="RdBu_r", fmt=".3f", cbar_label="AUC-ROC",
        col_sep=[1, 3],
    )

    # Panel d — Spearman ρ heatmap (spans both cols, row 2)
    ax_d = fig.add_subplot(gs[2, :])
    draw_heatmap(
        ax_d, rho_mat, HM_LM_DISPLAY, DATASETS_RHO,
        title        = ("IPI PSR Transformer Model Validation on External Clinical Antibodies  —  "
                        "Spearman ρ  (P(PASS) vs polyreactivity assay score)"),
        panel_letter = "d",
        vmin=-0.80, vmax=0.20, vcenter=0.0,
        cmap="RdBu_r", fmt=".2f", cbar_label="Spearman ρ",
        cbar_ticks   = [-0.8, -0.6, -0.4, -0.2, 0.0, 0.1, 0.2],
        pval_mat     = pval_mat,
        col_sep      = [1, 3],
    )

    print(f"\n[Combined Figure 4]")
    save_combined(fig, out, dpi)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--excel", default="Figure4_data.xlsx")
    parser.add_argument("--out",   default="Figure4")
    parser.add_argument("--dpi",   type=int, default=300)
    parser.add_argument("--jain",  default="Jain2017_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx")
    parser.add_argument("--gdpa1", default="GDPa1_v1_3_20251027_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx")
    parser.add_argument("--panels-only", dest="panels_only", action="store_true",
                        help="Save only separate panel files, skip combined figure")
    parser.add_argument("--gdpa3", default="GDPa3_20260106_pred_psr_filter_all_transformer_lm_ipi_psr_trainset.xlsx")
    args = parser.parse_args()

    # ── Load data (same as original) ─────────────────────────────────────────
    df_cv, df_xfer = load_data(args.excel)

    jain  = pd.read_excel(args.jain)
    gdpa1 = pd.read_excel(args.gdpa1)
    gdpa3 = pd.read_excel(args.gdpa3)
    gdpa1["psr_filter_ova"] = (gdpa1["polyreactivity_prscore_ova_avg"] < THRESH).astype(float)
    gdpa1["psr_filter_cho"] = (gdpa1["polyreactivity_prscore_cho_avg"] < THRESH).astype(float)

    auc_mat, rho_mat, pval_mat = compute_heatmap_matrices(jain, gdpa1, gdpa3)
    groups_a = build_groups_a(df_cv)
    groups_b = build_groups_b(df_xfer)

    # ─────────────────────────────────────────────────────────────────────────
    # PANEL a — standalone figure
    # Same size ratio as original (wider than tall — bar chart)
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n[Panel a]  IPI PSR 10-Fold CV bar chart")
    fig_a, ax_a = plt.subplots(figsize=(FW, FH * 1.1))
    fig_a.subplots_adjust(left=0.10, right=0.96, top=0.92, bottom=0.28)
    draw_bar_panel(
        ax_a, groups_a,
        title        = "IPI PSR Dataset · 10-Fold HCDR3-Stratified CV",
        panel_letter = "",
        ylim         = (0.0, 1.02),
        ref_auc      = 0.960,
        ref_acc      = 0.900,
        group_col    = ARCH_COL,
    )
    save_panel(fig_a, f"{args.out}_panel_a", args.dpi)

    # ─────────────────────────────────────────────────────────────────────────
    # PANEL b — standalone figure
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n[Panel b]  Cross-Dataset Generalization bar chart")
    fig_b, ax_b = plt.subplots(figsize=(FW * 0.65, FH * 1.1))
    fig_b.subplots_adjust(left=0.12, right=0.96, top=0.92, bottom=0.28)
    draw_bar_panel(
        ax_b, groups_b,
        title        = "Cross-Dataset Generalization · Transformer",
        panel_letter = "",
        ylim         = (0.0, 1.02),
        ref_auc      = 0.90,
        ref_acc      = None,
        group_col    = COND_COL,
    )
    save_panel(fig_b, f"{args.out}_panel_b", args.dpi)

    # ─────────────────────────────────────────────────────────────────────────
    # PANEL c — standalone figure (AUC-ROC heatmap)
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n[Panel c]  Clinical AUC-ROC heatmap")
    fig_c, ax_c = plt.subplots(figsize=(FW, FH * 0.65))
    fig_c.subplots_adjust(left=0.14, right=0.95, top=0.82, bottom=0.26)
    draw_heatmap(
        ax_c, auc_mat, HM_LM_DISPLAY, DATASETS_AUC,
        title        = (f'IPI PSR Transformer Model Validation on External Clinical Antibodies  —  '
                        f'AUC-ROC  (PASS: PSR/PR score <{THRESH}; ELISA <{THRESH_ELISA})'),
        panel_letter = "",
        vmin=0.20, vmax=0.90, vcenter=0.55,
        cmap='RdBu_r', fmt='.3f', cbar_label='AUC-ROC',
        col_sep      = [1, 3],
        grp_labels   = None,
    )
    save_panel(fig_c, f"{args.out}_panel_c", args.dpi)

    # ─────────────────────────────────────────────────────────────────────────
    # PANEL d — standalone figure (Spearman ρ heatmap)
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n[Panel d]  Clinical Spearman ρ heatmap")
    fig_d, ax_d = plt.subplots(figsize=(FW, FH * 0.65))
    fig_d.subplots_adjust(left=0.14, right=0.95, top=0.82, bottom=0.26)
    draw_heatmap(
        ax_d, rho_mat, HM_LM_DISPLAY, DATASETS_RHO,
        title        = ('IPI PSR Transformer Model Validation on External Clinical Antibodies  —  '
                        'Spearman ρ  (P(PASS) vs polyreactivity assay score)'),
        panel_letter = "",
        vmin=-0.80, vmax=0.20, vcenter=0.0,
        cmap='RdBu_r', fmt='.2f', cbar_label='Spearman ρ',
        cbar_ticks   = [-0.8, -0.6, -0.4, -0.2, 0.0, 0.1, 0.2],
        pval_mat     = pval_mat,
        col_sep      = [1, 3],
        grp_labels   = None,
    )
    save_panel(fig_d, f"{args.out}_panel_d", args.dpi)

    print(f"\n✓  All 4 panels saved.  Re-run with --dpi 600 for print quality.")

    # ─────────────────────────────────────────────────────────────────────────
    # COMBINED FIGURE — all 4 panels in one file (default: also generated)
    # ─────────────────────────────────────────────────────────────────────────
    if not args.panels_only:
        make_combined_figure(
            groups_a, groups_b,
            auc_mat, rho_mat, pval_mat,
            out = args.out,
            dpi = args.dpi,
        )
        print(f"\n✓  Combined Figure 4 saved.")


if __name__ == "__main__":
    main()
